### ISSUE TITLE
GrpcMock Junit, UNAVAILABLE: No servers found when running tests in --parallel

### ISSUE THREAD

**Issue by fercam24** [Fadelis/grpcmock#11]
Hi all,
I actually have some problems running my tests with **gradle --parallel** option. Without it, everything works fine, with it I continuously get 

```
io.grpc.StatusRuntimeException: UNAVAILABLE: No servers found for localhost:62497
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)

```

Here is how I set my tests

```
@ExtendWith({MockitoExtension.class, GrpcMockExtension.class})
public class TicketServiceTest implements WithAssertions {

	private ManagedChannel frontendChannel;
	private ManagedChannel backendChannel;

	@BeforeEach
	public void setUp() {
		frontendChannel = buildManagedChannel();
		backendChannel = buildManagedChannel();

                val frontendStub = FrontendServiceGrpc.newBlockingStub(frontendChannel);
		val backendStub = BackendServiceGrpc.newBlockingStub(backendChannel);
                ...
	}

	@AfterEach
	void cleanup() {
		val channels = List.of(frontendChannel, backendChannel);
		channels.forEach(managedChannel -> Optional.ofNullable(managedChannel).ifPresent(ManagedChannel::shutdownNow));
	}

	private ManagedChannel buildManagedChannel() {
		return ManagedChannelBuilder.forAddress("localhost", GrpcMock.getGlobalPort())
									.usePlaintext()
									.build();
	}
}
```

Do you guys have any idea?

**Comment by Fadelis** [comment]
@fercam24 Most probably you have a similar issue as described in https://github.com/Fadelis/grpcmock/issues/8 . Since the `static` methods (like `getGlobalPort`) are based on `ThreadLocal`, each parallel execution has it's own instance, and only a single one of those is a running server configured via Junit's `GrpcMockExtension`.

**Comment by ddeath** [comment]
Maybe this will be helpful for some else, but you can do also this is kotlin:

```kotlin
@SpringBootTest(
    classes = [TestApplication::class],
    useMainMethod = ALWAYS,
    webEnvironment = SpringBootTest.WebEnvironment.NONE,
)
@AutoConfigureGrpcMock
abstract class AbstractSingleServiceTest {
    @Autowired
    lateinit var grpcMock: GrpcMock

    companion object {
        @JvmStatic
        @DynamicPropertySource
        fun properties(registry: DynamicPropertyRegistry) {
            val grpcRandomPort: Int = TestSocketUtils.findAvailableTcpPort()

            registry.add("grpcmock.server.port") { grpcRandomPort }
            registry.add("grpcmock.server.port-dynamic") { true }

            registry.add("grpc.client.xxx.address") { "static://localhost:$grpcRandomPort" }
        }
    }
}
```

Setting `grpcmock.server.port` and `grpcmock.server.port-dynamic` this way will make sure that those properties are available for your application sooner then normal.
This library is setting them but too late - after context is build which is too late for some things - for example if you are creating your grpc clients with `@GrpcClient` and you need to set those properties `grpc.client.xxx....`
